package bd.dms.metrics;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

/**
 * The consolidated output of ticket 14's validation harness: every quantitative gate the other
 * feature tickets already measure individually (forecast accuracy, anomaly-detector accuracy,
 * the allocation priority-vs-FCFS comparison), gathered into one artifact instead of scattered
 * across {@code System.out.println} lines in five separate test classes. Written by
 * {@code bd.dms.anomaly.MetricsReportGeneratorTest}, which is the actual scenario runner —
 * this class only knows how to hold the numbers and render them.
 */
public record MetricsReport(
        Map<String, Double> forecastMaeByDataQualityCondition,
        List<DetectorAccuracy> detectorAccuracy,
        AllocationComparison allocationComparison) {

    public record DetectorAccuracy(
            String detector, double precision, double recall, double falsePositiveRate, long leadTimeTicks) {}

    public record AllocationComparison(double fcfsUnmetSeverityWeighted, double priorityUnmetSeverityWeighted) {}

    /** Writes both {@code metrics-report.json} (machine-readable, for CI to archive) and
     * {@code metrics-report.md} (the human-readable table this ticket's doc requires) into
     * {@code dir}, creating it if needed. */
    public void writeTo(Path dir) {
        try {
            Files.createDirectories(dir);
            ObjectMapper mapper = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);
            Files.writeString(dir.resolve("metrics-report.json"), mapper.writeValueAsString(this));
            Files.writeString(dir.resolve("metrics-report.md"), toMarkdown());
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private String toMarkdown() {
        StringBuilder md = new StringBuilder();
        md.append("# Metrics report\n\n");
        md.append("Generated by `MetricsReportGeneratorTest` — see `docs/metrics-report.md` for the ")
                .append("narrative version of this same run.\n\n");

        md.append("## Forecast MAE by data-quality condition\n\n");
        md.append("| Condition | MAE |\n|---|---|\n");
        forecastMaeByDataQualityCondition()
                .forEach((condition, mae) -> md.append("| %s | %.3f |\n".formatted(condition, mae)));

        md.append("\n## Anomaly detector accuracy\n\n");
        md.append("| Detector | Precision | Recall | False-positive rate | Lead time (ticks/events) |\n");
        md.append("|---|---|---|---|---|\n");
        for (DetectorAccuracy d : detectorAccuracy()) {
            md.append("| %s | %.2f | %.2f | %.2f | %d |\n"
                    .formatted(d.detector(), d.precision(), d.recall(), d.falsePositiveRate(), d.leadTimeTicks()));
        }

        md.append("\n## Allocation: priority ordering vs. FCFS\n\n");
        md.append("| Strategy | Unmet severity-weighted shortage |\n|---|---|\n");
        md.append("| FCFS (camp-id order) | %.2f |\n".formatted(allocationComparison().fcfsUnmetSeverityWeighted()));
        md.append("| Priority-ranked | %.2f |\n".formatted(allocationComparison().priorityUnmetSeverityWeighted()));

        return md.toString();
    }
}
