-- Forecast observation history: one row per camp/resource/tick, appended by
-- SimulationEngine (the sole writer, mirroring how it already writes camp_resources).
-- Multiple rows can share the same tick for a camp/resource — that IS the "conflicting
-- reports" condition (two disagreeing readings for the same moment). A gap in tick numbers
-- for a camp/resource IS the "stale reports" condition (no reading was written for a while).
CREATE TABLE camp_resource_observations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camp_id       BIGINT        NOT NULL REFERENCES camps (id),
    resource_type VARCHAR(30)   NOT NULL,
    quantity      NUMERIC(12,2) NOT NULL,
    tick          BIGINT        NOT NULL,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cro_camp_resource_tick ON camp_resource_observations (camp_id, resource_type, tick);

-- A forecast-triggered alert has no human actor; NULL follows the same "system-triggered"
-- convention already used by alert_transitions.actor_user_id (see V9).
ALTER TABLE alerts ALTER COLUMN raised_by_user_id DROP NOT NULL;

-- Which resource a forecast-triggered RESOURCE_SHORTAGE alert is about. NULL for every
-- manually-raised alert (including manual RESOURCE_SHORTAGE) — it's what lets the forecast
-- alert listener dedupe per camp+type+resource instead of per camp+type.
ALTER TABLE alerts ADD COLUMN resource_type VARCHAR(30);
