-- Allocation decision queue (ticket 08): a pure decision-support ledger, never a second writer
-- of camp_resources — SimulationEngine.apply() unconditionally overwrites that table every tick,
-- so a physical-quantity writer here would be silently clobbered. Each row is a suggested
-- cross-camp redistribution (source_camp_id has surplus, target_camp_id has a shortage) of one
-- resource_type, ranked by priority_score. decided_quantity is null until a coordinator acts;
-- it equals recommended_quantity on APPROVED, a coordinator-chosen value on MODIFIED, and stays
-- null on REJECTED (nothing was decided to move).
CREATE TABLE allocation_decisions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_type         VARCHAR(30)    NOT NULL,
    source_camp_id        BIGINT         NOT NULL REFERENCES camps (id),
    target_camp_id        BIGINT         NOT NULL REFERENCES camps (id),
    recommended_quantity  NUMERIC(12,2)  NOT NULL,
    decided_quantity      NUMERIC(12,2),
    status                VARCHAR(20)    NOT NULL,
    severity_score        DOUBLE PRECISION NOT NULL,
    shortage_score        DOUBLE PRECISION NOT NULL,
    population_score      DOUBLE PRECISION NOT NULL,
    fairness_score        DOUBLE PRECISION NOT NULL,
    priority_score        DOUBLE PRECISION NOT NULL,
    generated_at_tick     BIGINT         NOT NULL,
    decided_at_tick       BIGINT,
    created_at            TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_allocation_decisions_source ON allocation_decisions (source_camp_id, resource_type, status);
CREATE INDEX idx_allocation_decisions_target ON allocation_decisions (target_camp_id, resource_type, status);

-- Audit timeline of an allocation's status changes — mirrors alert_transitions exactly.
-- actor_user_id NULL means system-generated (there is no system-driven transition today, since
-- generation only ever creates/refreshes RECOMMENDED rows directly, not via a transition row —
-- nullable purely for consistency with the established convention, in case a future ticket adds
-- an automated transition).
CREATE TABLE allocation_transitions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    allocation_id  BIGINT       NOT NULL REFERENCES allocation_decisions (id),
    from_status    VARCHAR(20)  NOT NULL,
    to_status      VARCHAR(20)  NOT NULL,
    actor_user_id  BIGINT,
    note           VARCHAR(2000),
    at_tick        BIGINT       NOT NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_allocation_transitions_allocation ON allocation_transitions (allocation_id, at_tick);
