-- Money model (ticket 10): donations accrue into a disaster-level fund ledger; procurement
-- spends against that ledger to notionally convert money into resourceType quantity for a camp.
-- Like allocation_decisions before it, procurements is a pure decision-support/ledger record —
-- it never touches camps/camp_resources, which stay SimulationEngine's alone. Both tables are
-- append-only: nothing here is ever updated or deleted, so the ledger balance (sum(donations) -
-- sum(procurements), per disaster) is always a simple, auditable aggregate.
CREATE TABLE donations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_user_id  BIGINT         NOT NULL REFERENCES users (id),
    disaster_id    BIGINT         NOT NULL REFERENCES disasters (id),
    amount         NUMERIC(14,2)  NOT NULL,
    created_at     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_donations_disaster ON donations (disaster_id);
CREATE INDEX idx_donations_donor ON donations (donor_user_id);

-- unit_price/quantity are recorded at procurement time (not looked up again later), so a report
-- run afterwards reproduces exactly what happened even if prices changed since.
CREATE TABLE procurements (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disaster_id    BIGINT         NOT NULL REFERENCES disasters (id),
    camp_id        BIGINT         NOT NULL REFERENCES camps (id),
    resource_type  VARCHAR(30)    NOT NULL,
    amount         NUMERIC(14,2)  NOT NULL,
    unit_price     NUMERIC(14,4)  NOT NULL,
    quantity       NUMERIC(14,2)  NOT NULL,
    actor_user_id  BIGINT         NOT NULL REFERENCES users (id),
    created_at     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_procurements_disaster ON procurements (disaster_id);
CREATE INDEX idx_procurements_camp ON procurements (camp_id);
