-- Volunteer matching (ticket 09): a roster of volunteer profiles (distinct from login users —
-- mirrors family members not being users) and a task queue derived from alerts. Never writes
-- camps/camp_resources — SimulationEngine.apply() stays the sole writer of those.
CREATE TABLE volunteer_profiles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(60)  NOT NULL UNIQUE,
    user_id    BIGINT REFERENCES users (id),
    name_en    VARCHAR(150) NOT NULL,
    name_bn    VARCHAR(150) NOT NULL,
    lat        DOUBLE PRECISION NOT NULL,
    lng        DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_volunteer_profiles_user ON volunteer_profiles (user_id);

-- One row per skill a volunteer holds (a person can hold several).
CREATE TABLE volunteer_skills (
    volunteer_id BIGINT      NOT NULL REFERENCES volunteer_profiles (id),
    skill        VARCHAR(30) NOT NULL,
    PRIMARY KEY (volunteer_id, skill)
);

-- One open "shift" per open alert that maps to a skill (see VolunteerTaskGenerationService).
-- Never a second writer of alerts — alert_id is a read-only reference.
CREATE TABLE volunteer_tasks (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id              BIGINT       NOT NULL REFERENCES alerts (id),
    camp_id               BIGINT       NOT NULL REFERENCES camps (id),
    required_skill        VARCHAR(30)  NOT NULL,
    description            VARCHAR(2000) NOT NULL,
    status                VARCHAR(20)  NOT NULL,
    assigned_volunteer_id BIGINT REFERENCES volunteer_profiles (id),
    assignment_method     VARCHAR(10),
    urgency_score         DOUBLE PRECISION NOT NULL,
    generated_at_tick     BIGINT       NOT NULL,
    assigned_at_tick      BIGINT,
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (alert_id)
);

CREATE INDEX idx_volunteer_tasks_status ON volunteer_tasks (status);
CREATE INDEX idx_volunteer_tasks_assigned ON volunteer_tasks (assigned_volunteer_id);

-- Audit timeline of a task's status changes — mirrors allocation_transitions/alert_transitions.
CREATE TABLE volunteer_task_transitions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id        BIGINT       NOT NULL REFERENCES volunteer_tasks (id),
    from_status    VARCHAR(20)  NOT NULL,
    to_status      VARCHAR(20)  NOT NULL,
    actor_user_id  BIGINT,
    note           VARCHAR(2000),
    at_tick        BIGINT       NOT NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_volunteer_task_transitions_task ON volunteer_task_transitions (task_id, at_tick);
