-- Ticket 12, tiers 2 and 3: broadcast announcements (with read receipts) and narrow 1:1 DMs.
-- Tier 1 (case notes on alerts/allocations/transfers) needed no migration — it reuses the
-- already-generic `notes` table from V9 with a second `subject_type` value.

-- A bilingual announcement from a Coordinator/Admin to every Camp Manager or every Volunteer.
-- target_role is always CAMP_MANAGER or VOLUNTEER, enforced in BroadcastService, not here.
CREATE TABLE broadcasts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_user_id  BIGINT       NOT NULL REFERENCES users (id),
    target_role     VARCHAR(20)  NOT NULL,
    body_en         VARCHAR(2000) NOT NULL,
    body_bn         VARCHAR(2000) NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_broadcasts_target_role ON broadcasts (target_role, created_at);

-- One row per recipient who has actually opened a broadcast, so the sender can see who has
-- read it. Absence of a row means unread; there is no separate "delivered" state.
CREATE TABLE broadcast_reads (
    broadcast_id BIGINT    NOT NULL REFERENCES broadcasts (id),
    user_id      BIGINT    NOT NULL REFERENCES users (id),
    read_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (broadcast_id, user_id)
);

-- Narrow 1:1 messages. Only permitted along a genuine operational relationship (Coordinator <->
-- Camp Manager, Camp Manager <-> their Volunteers) — enforced in DmRelationshipService at
-- send/read time, not by a constraint here, since the relationship depends on camp_assignments
-- rather than anything this table alone can express.
CREATE TABLE direct_messages (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_user_id     BIGINT        NOT NULL REFERENCES users (id),
    recipient_user_id  BIGINT        NOT NULL REFERENCES users (id),
    body               VARCHAR(2000) NOT NULL,
    created_at         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_dm_sender ON direct_messages (sender_user_id, recipient_user_id, created_at);
CREATE INDEX idx_dm_recipient ON direct_messages (recipient_user_id, sender_user_id, created_at);
