-- Anomaly detection (ticket 11): flag-for-review only. Detectors never mutate camps,
-- camp_resources, allocation_decisions, family_groups, family_members, or donations — they only
-- ever read those tables and write a row here. innocent_explanation is a static string per
-- detector_type, always non-null, so the reviewer sees the counter-argument next to the evidence.
CREATE TABLE anomaly_flags (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detector_type         VARCHAR(30)   NOT NULL,
    score                 DOUBLE PRECISION NOT NULL,
    summary               VARCHAR(2000) NOT NULL,
    innocent_explanation  VARCHAR(2000) NOT NULL,
    detected_at_tick      BIGINT,
    status                VARCHAR(20)   NOT NULL DEFAULT 'OPEN',
    reviewed_by_user_id   BIGINT REFERENCES users (id),
    review_note           VARCHAR(2000),
    reviewed_at           TIMESTAMP,
    created_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_anomaly_flags_detector_type ON anomaly_flags (detector_type, created_at);
CREATE INDEX idx_anomaly_flags_status ON anomaly_flags (status);

-- The evidence row ids behind a flag; meaning depends on anomaly_flags.detector_type
-- (allocation-decision ids / family-group ids / donation ids).
CREATE TABLE anomaly_flag_subjects (
    anomaly_flag_id BIGINT NOT NULL REFERENCES anomaly_flags (id),
    subject_id      BIGINT NOT NULL
);

CREATE INDEX idx_anomaly_flag_subjects_flag ON anomaly_flag_subjects (anomaly_flag_id);
