-- Manual disaster registration (ticket 13): admins declare/edit disasters directly and
-- coordinators propose changes for a central authority to approve. disasters.geometry is the
-- admin-drawn boundary polygon, nullable because the two seeded demo disasters predate it.
-- geometry_history is one generic append-only audit trail for every geometry write (mirrors
-- alert_transitions), covering both disasters and affected areas so neither needs its own
-- history table. disaster_proposals is the coordinator -> central-authority approval queue;
-- payload is the JSON body the matching admin endpoint accepts, so approval can replay it
-- verbatim through the same write path used for direct admin edits.
ALTER TABLE disasters ADD COLUMN geometry TEXT;

CREATE TABLE geometry_history (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_type       VARCHAR(20) NOT NULL,  -- DISASTER | AFFECTED_AREA
    subject_id         BIGINT      NOT NULL,
    previous_geometry  TEXT,
    new_geometry       TEXT        NOT NULL,
    actor_user_id      BIGINT      NOT NULL REFERENCES users (id),
    created_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE disaster_proposals (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_type         VARCHAR(30)   NOT NULL,  -- DISASTER_CREATE | DISASTER_UPDATE | DISASTER_CLOSE | AFFECTED_AREA_CREATE | CAMP_CREATE
    target_disaster_id    BIGINT        REFERENCES disasters (id),  -- NULL for DISASTER_CREATE
    payload               TEXT          NOT NULL,
    status                VARCHAR(20)   NOT NULL DEFAULT 'PENDING',  -- PENDING | APPROVED | REJECTED
    proposed_by_user_id   BIGINT        NOT NULL REFERENCES users (id),
    created_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_by_user_id   BIGINT        REFERENCES users (id),
    reviewed_at           TIMESTAMP,
    review_note           TEXT
);

CREATE INDEX idx_geometry_history_subject ON geometry_history (subject_type, subject_id);
CREATE INDEX idx_disaster_proposals_status ON disaster_proposals (status);
CREATE INDEX idx_disaster_proposals_target_disaster ON disaster_proposals (target_disaster_id);
