-- Auth schema: the demo's seven seeded users and their revocable refresh tokens.
-- Portable DDL so the identical migration applies on Postgres (runtime) and H2 (tests).
-- Seed rows are inserted by DemoUserSeeder at startup (hashing with the real PasswordEncoder),
-- not here, so no bcrypt digests are baked into the migration.
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(30)  NOT NULL,
    name_en       VARCHAR(150) NOT NULL,
    name_bn       VARCHAR(150) NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(100) NOT NULL UNIQUE,
    user_id    BIGINT       NOT NULL REFERENCES users (id),
    expires_at TIMESTAMP    NOT NULL,
    revoked    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
