-- World schema: the shared model every later feature reads from — disasters, their affected
-- areas (geometry), the relief camps inside them, and a per-camp resource summary.
-- Portable DDL so the identical migration applies on Postgres (runtime) and H2 (tests).
-- Geometry is stored as GeoJSON text: a read-only Leaflet render needs no spatial queries,
-- so this stays portable and the client gets a geometry object it can draw directly.
CREATE TABLE disasters (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(60)  NOT NULL UNIQUE,
    type        VARCHAR(20)  NOT NULL,   -- FLOOD | CYCLONE
    status      VARCHAR(20)  NOT NULL,   -- ACTIVE | STABLE (headline state)
    name_en     VARCHAR(150) NOT NULL,
    name_bn     VARCHAR(150) NOT NULL,
    declared_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE affected_areas (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disaster_id BIGINT       NOT NULL REFERENCES disasters (id),
    name_en     VARCHAR(150) NOT NULL,
    name_bn     VARCHAR(150) NOT NULL,
    geometry    TEXT         NOT NULL   -- GeoJSON Polygon
);

CREATE TABLE camps (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disaster_id BIGINT        NOT NULL REFERENCES disasters (id),
    code        VARCHAR(60)   NOT NULL UNIQUE,
    name_en     VARCHAR(150)  NOT NULL,
    name_bn     VARCHAR(150)  NOT NULL,
    lat         NUMERIC(9, 6) NOT NULL,
    lng         NUMERIC(9, 6) NOT NULL,
    capacity    INTEGER       NOT NULL,
    population  INTEGER       NOT NULL,
    status      VARCHAR(20)   NOT NULL   -- OPEN | CLOSED
);

CREATE TABLE camp_resources (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camp_id       BIGINT         NOT NULL REFERENCES camps (id),
    resource_type VARCHAR(30)    NOT NULL,   -- WATER | FOOD | MEDICAL | SHELTER
    quantity      NUMERIC(12, 2) NOT NULL,
    unit          VARCHAR(30)    NOT NULL
);

CREATE INDEX idx_affected_areas_disaster ON affected_areas (disaster_id);
CREATE INDEX idx_camps_disaster ON camps (disaster_id);
CREATE INDEX idx_camp_resources_camp ON camp_resources (camp_id);
