-- Victim/family registration, the first user-driven world mutation. Deliberately separate
-- from camps/camp_resources (the simulation engine's sole-writer tables) so the two writers
-- cannot collide: a family group records intent to arrive at a camp, never the camp's own
-- population. member_count is intentionally NOT a column here — it is always derived from
-- family_members so it cannot drift from the roster.
CREATE TABLE family_groups (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id            BIGINT       NOT NULL UNIQUE REFERENCES users (id),
    camp_id                  BIGINT       NOT NULL REFERENCES camps (id),
    group_name               VARCHAR(150) NOT NULL,
    representative_arrived   BOOLEAN      NOT NULL DEFAULT FALSE,
    manager_confirmed_arrived BOOLEAN     NOT NULL DEFAULT FALSE,
    registered_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE family_members (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_group_id BIGINT      NOT NULL REFERENCES family_groups (id),
    nickname        VARCHAR(80) NOT NULL,
    age_band        VARCHAR(20) NOT NULL,   -- CHILD | ADULT | ELDER
    medical_flag    BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_family_groups_camp ON family_groups (camp_id);
CREATE INDEX idx_family_members_group ON family_members (family_group_id);
