-- Alert lifecycle: an Alert moves New -> Acknowledged -> In Progress -> Resolved/Escalated ->
-- Closed. alert_transitions IS the audit timeline (no separate audit table). notes is a
-- generic threaded-note mechanism (subject_type/subject_id) so ticket 12's allocation/transfer
-- comms can reuse it without a migration. Portable DDL (Postgres + H2).
CREATE TABLE alerts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type              VARCHAR(30)  NOT NULL,  -- RESOURCE_SHORTAGE | MEDICAL_EMERGENCY | SECURITY_INCIDENT | INFRASTRUCTURE_DAMAGE
    camp_id           BIGINT       NOT NULL REFERENCES camps (id),
    status            VARCHAR(20)  NOT NULL,  -- NEW | ACKNOWLEDGED | IN_PROGRESS | RESOLVED | ESCALATED | CLOSED
    description       VARCHAR(2000) NOT NULL,
    raised_by_user_id BIGINT       NOT NULL REFERENCES users (id),
    raised_at_tick    BIGINT       NOT NULL,
    sla_deadline_tick BIGINT       NOT NULL,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE alert_transitions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id       BIGINT      NOT NULL REFERENCES alerts (id),
    from_status    VARCHAR(20) NOT NULL,
    to_status      VARCHAR(20) NOT NULL,
    actor_user_id  BIGINT      REFERENCES users (id),  -- NULL means system/SLA-triggered
    note           VARCHAR(2000),
    at_tick        BIGINT      NOT NULL,
    created_at     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_type    VARCHAR(20) NOT NULL,  -- ALERT (more subject types arrive in later tickets)
    subject_id      BIGINT      NOT NULL,
    author_user_id  BIGINT      NOT NULL REFERENCES users (id),
    body            VARCHAR(4000) NOT NULL,
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_alerts_camp ON alerts (camp_id);
CREATE INDEX idx_alerts_status ON alerts (status);
CREATE INDEX idx_alert_transitions_alert ON alert_transitions (alert_id);
CREATE INDEX idx_notes_subject ON notes (subject_type, subject_id);
